language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
notifications:
  irc: "chat.eu.freenode.net#vizicities"
  webhooks:
    urls:
      - http://surveyor-hubot.apps.rawk.es/hubot/travis?room=%23vizicities
      - https://vizicities.slack.com/services/hooks/travis?token=RGVKvriXw709tZ496MfHw34a
    on_success: always
    on_failure: always
    on_start: true