language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
notifications:
  irc: "chat.eu.freenode.net#vizicities"
  webhooks: http://surveyor-hubot.apps.rawk.es/hubot/travis?room=1