language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
notifications:
  email:
    recipients:
      - robin@vizicities.com
    on_success: always
    on_failure: always
  irc: "chat.eu.freenode.net#vizicities"